twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - 'bootstrap_5_layout.html.twig'
    # Ajout du service à l'environnement Twig
    globals:
        user: '@App\Services\UserService'

when@test:
    twig:
        strict_variables: true

